const baseData = [
  {
    mark: "SA",
    Locale: "ar",
    label: "Arabic",
    "Apply Now": "اشترك الآن",
    "Book Now": "احجز الآن",
    "Contact Us": "اتصل بنا",
    Download: "تنزيل",
    "Learn More": "معلومات أكثر",
    Install: "تثبيت",
    "Visit Site": "زيارة الموقع",
    "Shop Now": "التسوق الآن",
    "Sign Up": "الاشتراك",
    "Get Quote": "حصول على سعر",
    Subscribe: "اشتراك",
    "See More": "معرفة المزيد",
  },
  {
    Locale: "bg",
    "Apply Now": "Кандидатствайте сега",
    "Book Now": "Резерв. сега",
    "Contact Us": "Връзка с нас",
    Download: "Изтеглете",
    "Learn More": "Научете повече",
    Install: "Инсталирайте",
    "Visit Site": "Посетете сайта",
    "Shop Now": "Купете сега",
    "Sign Up": "",
    "Get Quote": "Получете оферта",
    Subscribe: "Абонирайте се",
    "See More": "Вижте още",
    label: "Bulgarian",
  },
  {
    Locale: "ca",
    "Apply Now": "Sol·liciteu-ho",
    "Book Now": "Reserveu-ho",
    "Contact Us": "Contacteu",
    Download: "Baixa",
    "Learn More": "Més informació",
    Install: "Instal·la",
    "Visit Site": "Visiteu el lloc",
    "Shop Now": "Compreu ara",
    "Sign Up": "Registreu-vos",
    "Get Quote": "Pressupost",
    Subscribe: "Subscriviu-vos",
    "See More": "Mostra més",
    label: "Catalan",
  },
  {
    Locale: "cs",
    "Apply Now": "Přihlaste se",
    "Book Now": "Rezervujte hned",
    "Contact Us": "Kontaktujte nás",
    Download: "Stáhnout",
    "Learn More": "Další informace",
    Install: "Nainstalovat",
    "Visit Site": "Přejít na web",
    "Shop Now": "Kupujte nyní",
    "Sign Up": "Registrujte se",
    "Get Quote": "Cenová nabídka",
    Subscribe: "Odebírejte",
    "See More": "Zobrazit více",
    label: "Czech",
  },
  {
    Locale: "da",
    "Apply Now": "Ansøg nu",
    "Book Now": "Bestil nu",
    "Contact Us": "Kontakt os",
    Download: "Download",
    "Learn More": "Læs mere",
    Install: "Installer",
    "Visit Site": "Besøg website",
    "Shop Now": "Køb nu",
    "Sign Up": "Registrer",
    "Get Quote": "Hent tilbud",
    Subscribe: "Abonner",
    "See More": "Se flere",
    label: "Danish",
  },
  {
    mark: "DE",
    Locale: "de",
    "Apply Now": "Jetzt bewerben",
    "Book Now": "Jetzt buchen",
    "Contact Us": "Kontakt",
    Download: "Herunterladen",
    "Learn More": "Weitere Infos",
    Install: "Installieren",
    "Visit Site": "Zur Website",
    "Shop Now": "Jetzt einkaufen",
    "Sign Up": "Anmelden",
    "Get Quote": "Angebot anfordern",
    Subscribe: "Abonnieren",
    "See More": "Mehr",
    label: "German",
  },
  {
    Locale: "el",
    "Apply Now": "Αίτηση τώρα",
    "Book Now": "Κράτηση τώρα",
    "Contact Us": "Επικοινωνία",
    Download: "Λήψη",
    "Learn More": "Μάθετε περισ.",
    Install: "Εγκατάσταση",
    "Visit Site": "Επίσκεψη ιστοτ.",
    "Shop Now": "Αγορά τώρα",
    "Sign Up": "Εγγραφείτε",
    "Get Quote": "Λήψη προσφοράς",
    Subscribe: "Εγγραφή",
    "See More": "Δείτε περισ",
    label: "Greek",
  },
  {
    mark: "US",
    Locale: "en",
    "Apply Now": "Apply Now",
    "Book Now": "Book Now",
    "Contact Us": "Contact Us",
    Download: "Download",
    "Learn More": "Learn More",
    Install: "Install",
    "Visit Site": "Visit Site",
    "Shop Now": "Shop Now",
    "Sign Up": "Sign Up",
    "Get Quote": "Get Quote",
    Subscribe: "Subscribe",
    "See More": "See More",
    label: "English (US)",
  },
  {
    Locale: "en-AU",
    "Apply Now": "Apply Now",
    "Book Now": "Book Now",
    "Contact Us": "Contact Us",
    Download: "Download",
    "Learn More": "Learn More",
    Install: "Install",
    "Visit Site": "Visit Site",
    "Shop Now": "Shop Now",
    "Sign Up": "Sign up",
    "Get Quote": "Get Quote",
    Subscribe: "Subscribe",
    "See More": "See More",
    label: "English (AU)",
  },
  {
    Locale: "en-GB",
    "Apply Now": "Apply now",
    "Book Now": "Book now",
    "Contact Us": "Contact us",
    Download: "Download",
    "Learn More": "Learn more",
    Install: "Install",
    "Visit Site": "Visit site",
    "Shop Now": "Shop now",
    "Sign Up": "Sign up",
    "Get Quote": "Get quote",
    Subscribe: "Subscribe",
    "See More": "See more",
    label: "English (UK)",
  },
  {
    mark: "ES",
    Locale: "es",
    "Apply Now": "Aplicar",
    "Book Now": "Reservar",
    "Contact Us": "Contacto",
    Download: "Descargar",
    "Learn More": "Más información",
    Install: "Instalar",
    "Visit Site": "Visitar sitio",
    "Shop Now": "Comprar",
    "Sign Up": "Registrarse",
    "Get Quote": "Pedir precios",
    Subscribe: "Suscribirse",
    "See More": "Ver más",
    label: "Spanish",
  },
  {
    Locale: "es-419",
    "Apply Now": "Suscríbase",
    "Book Now": "Reserve ahora",
    "Contact Us": "Contáctenos",
    Download: "Descargar",
    "Learn More": "Más información",
    Install: "Instalar",
    "Visit Site": "Visite el sitio",
    "Shop Now": "Compre ahora",
    "Sign Up": "Regístrese",
    "Get Quote": "Cotice ahora",
    Subscribe: "Suscríbase",
    "See More": "Ver más",
    label: "Spanish (419)",
  },
  {
    Locale: "et",
    "Apply Now": "Rakenda kohe",
    "Book Now": "Broneeri kohe!",
    "Contact Us": "Võtke ühendust",
    Download: "Allalaadimine",
    "Learn More": "Lisateave",
    Install: "Installi",
    "Visit Site": "Külastage saiti",
    "Shop Now": "Külastage poodi",
    "Sign Up": "Registreeruge",
    "Get Quote": "Hinnapakkumine",
    Subscribe: "Tellige",
    "See More": "",
    label: "Estonian",
  },
  {
    mark: "FI",
    Locale: "fi",
    "Apply Now": "Hae nyt",
    "Book Now": "Varaa nyt",
    "Contact Us": "Ota yhteyttä",
    Download: "Lataa",
    "Learn More": "Lisätietoja",
    Install: "Asenna",
    "Visit Site": "Sivustolle",
    "Shop Now": "Osta nyt",
    "Sign Up": "Rekisteröidy",
    "Get Quote": "Pyydä tarjous",
    Subscribe: "Tilaa",
    "See More": "Näytä lisää",
    label: "Finnish",
  },
  {
    Locale: "fil",
    "Apply Now": "Mag-apply Na",
    "Book Now": "Mag-book Na",
    "Contact Us": "Kontakin Kami",
    Download: "I-download",
    "Learn More": "Matuto Pa",
    Install: "I-install",
    "Visit Site": "Pumunta sa Site",
    "Shop Now": "Mamili Na",
    "Sign Up": "Mag-sign Up",
    "Get Quote": "Kumuha ng Quote",
    Subscribe: "Mag-subscribe",
    "See More": "Tumingin Pa",
    label: "Filipino",
  },
  {
    mark: "FR",
    Locale: "fr",
    "Apply Now": "S'inscrire",
    "Book Now": "Réserver",
    "Contact Us": "Nous contacter",
    Download: "Télécharger",
    "Learn More": "En savoir plus",
    Install: "Installer",
    "Visit Site": "Visiter le site",
    "Shop Now": "Acheter",
    "Sign Up": "",
    "Get Quote": "Devis",
    Subscribe: "S'abonner",
    "See More": "Autres",
    label: "French",
  },
  {
    Locale: "hi",
    "Apply Now": "अभी लागू करें",
    "Book Now": "अभी बुक करें",
    "Contact Us": "हमसे संपर्क करें",
    Download: "डाउनलोड करें",
    "Learn More": "अधिक जानें",
    Install: "इंस्टॉल करें",
    "Visit Site": "साइट पर जाएं",
    "Shop Now": "अभी खरीदें",
    "Sign Up": "साइन अप करें",
    "Get Quote": "कोटेशन पाएं",
    Subscribe: "सदस्यता लें",
    "See More": "और देखें",
    label: "Hindi",
  },
  {
    Locale: "hr",
    "Apply Now": "Prijavite se",
    "Book Now": "Rezervirajte",
    "Contact Us": "Kontakt. nas",
    Download: "Preuzmi",
    "Learn More": "Saznajte više",
    Install: "Instaliraj",
    "Visit Site": "Posjet lokaciji",
    "Shop Now": "Kupite odmah",
    "Sign Up": "Registracija",
    "Get Quote": "Zatraži ponudu",
    Subscribe: "Pretplatite se",
    "See More": "Prikaži više",
    label: "Croatian",
  },
  {
    Locale: "hu",
    "Apply Now": "Jelentkezés",
    "Book Now": "Foglalás",
    "Contact Us": "Kapcsolat",
    Download: "Letöltés",
    "Learn More": "Bővebben",
    Install: "Telepítés",
    "Visit Site": "Webhelyre",
    "Shop Now": "Vásárlás",
    "Sign Up": "Feliratkozás",
    "Get Quote": "Ajánlatkérés",
    Subscribe: "",
    "See More": "",
    label: "Hungarian",
  },
  {
    mark: "ID",
    Locale: "id",
    "Apply Now": "Daftar Sekarang",
    "Book Now": "Pesan Sekarang",
    "Contact Us": "Hubungi Kami",
    Download: "Download",
    "Learn More": "Pelajari",
    Install: "Instal",
    "Visit Site": "Kunjungi Situs",
    "Shop Now": "Beli Sekarang",
    "Sign Up": "Daftar",
    "Get Quote": "Minta Penawaran",
    Subscribe: "Langganan",
    "See More": "Selengkapnya",
    label: "Indonesian",
  },
  {
    mark: "IT",
    Locale: "it",
    "Apply Now": "Iscriviti ora",
    "Book Now": "Prenota subito",
    "Contact Us": "Contattaci",
    Download: "Scarica",
    "Learn More": "Scopri di più",
    Install: "Installa",
    "Visit Site": "Visita il sito",
    "Shop Now": "Compra ora",
    "Sign Up": "Registrati",
    "Get Quote": "Preventivo",
    Subscribe: "Sottoscrivi",
    "See More": "Vedi altro",
    label: "Italian",
  },
  {
    Locale: "iw",
    "Apply Now": "אני רוצה להצטרף",
    "Book Now": "אני רוצה להזמין",
    "Contact Us": "איך אפשר לעזור?",
    Download: "הורדה",
    "Learn More": "מידע נוסף",
    Install: "התקנה",
    "Visit Site": "היית באתר שלנו?",
    "Shop Now": "אני רוצה לקנות",
    "Sign Up": "אני רוצה להירשם",
    "Get Quote": "בקשה להצעת מחיר",
    Subscribe: "להרשמה כמנוי",
    "See More": "עוד פרטים",
    label: "Hebrew",
  },
  {
    mark: "JP",
    Locale: "ja",
    "Apply Now": "今すぐ適用",
    "Book Now": "今すぐ予約",
    "Contact Us": "お問い合わせ",
    Download: "ダウンロード",
    "Learn More": "詳細",
    Install: "インストール",
    "Visit Site": "サイトを見る",
    "Shop Now": "今すぐ購入",
    "Sign Up": "お申し込み",
    "Get Quote": "お見積もり",
    Subscribe: "登録",
    "See More": "もっと見る",
    label: "Japanese",
  },
  {
    mark: "KR",
    Locale: "ko",
    "Apply Now": "적용하기",
    "Book Now": "예약하기",
    "Contact Us": "문의하기",
    Download: "다운로드하기",
    "Learn More": "자세히 알아보기",
    Install: "설치하기",
    "Visit Site": "사이트 방문하기",
    "Shop Now": "구매하기",
    "Sign Up": "가입하기",
    "Get Quote": "견적 받기",
    Subscribe: "구독하기",
    "See More": "더보기",
    label: "Korean",
  },
  {
    Locale: "lt",
    "Apply Now": "Taikyti dabar",
    "Book Now": "Užsisakyti",
    "Contact Us": "Susisiekite",
    Download: "Atsisiųsti",
    "Learn More": "Išsamiau",
    Install: "Įdiegti",
    "Visit Site": "Apsilankyti",
    "Shop Now": "Apsipirkti",
    "Sign Up": "Registruotis",
    "Get Quote": "Gauti pasiūlymą",
    Subscribe: "Prenumeruoti",
    "See More": "Žr. daugiau",
    label: "Lithuanian",
  },
  {
    Locale: "lv",
    "Apply Now": "Pieteikties",
    "Book Now": "Rezervēt tūlīt",
    "Contact Us": "Sazināties",
    Download: "Lejupielādēt",
    "Learn More": "Uzzināt vairāk",
    Install: "Instalēt",
    "Visit Site": "Apmeklēt vietni",
    "Shop Now": "Iepirkties",
    "Sign Up": "Reģistrēties",
    "Get Quote": "Uzzināt cenas",
    Subscribe: "Abonēt",
    "See More": "Skatīt vairāk",
    label: "Latvian",
  },
  {
    mark: "MS",
    Locale: "ms",
    "Apply Now": "Mohon Sekarang",
    "Book Now": "Tempah Sekarang",
    "Contact Us": "Hubungi Kami",
    Download: "Muat Turun",
    "Learn More": "Ketahui Lagi",
    Install: "Pasang",
    "Visit Site": "Lawati Tapak",
    "Shop Now": "Beli Sekarang",
    "Sign Up": "Daftar Diri",
    "Get Quote": "Minta Seb.Harga",
    Subscribe: "Langgan",
    "See More": "Lihat Lagi",
    label: "Malay",
  },
  {
    mark: "NL",
    Locale: "nl",
    "Apply Now": "Nu toepassen",
    "Book Now": "Nu boeken",
    "Contact Us": "Contact opnemen",
    Download: "Downloaden",
    "Learn More": "Meer informatie",
    Install: "Installeren",
    "Visit Site": "Site bezoeken",
    "Shop Now": "Nu winkelen",
    "Sign Up": "Aanmelden",
    "Get Quote": "Offerte vragen",
    Subscribe: "Abonneren",
    "See More": "Meer weergeven",
    label: "Dutch",
  },
  {
    Locale: "no",
    "Apply Now": "Bruk nå",
    "Book Now": "Bestill nå",
    "Contact Us": "Kontakt oss",
    Download: "Last ned",
    "Learn More": "Finn ut mer",
    Install: "Installer",
    "Visit Site": "Besøk nettsiden",
    "Shop Now": "Kjøp nå",
    "Sign Up": "Registrer deg",
    "Get Quote": "Få pristilbud",
    Subscribe: "Abonner",
    "See More": "Vis flere",
    label: "Norwegian",
  },
  {
    mark: "PL",
    Locale: "pl",
    "Apply Now": "Zgłoś się teraz",
    "Book Now": "Zarezerwuj",
    "Contact Us": "Kontakt z nami",
    Download: "Pobierz",
    "Learn More": "Więcej informacji",
    Install: "Zainstaluj",
    "Visit Site": "Otwórz stronę",
    "Shop Now": "Kup teraz",
    "Sign Up": "Zarejestruj się",
    "Get Quote": "Uzyskaj wycenę",
    Subscribe: "Subskrybuj",
    "See More": "Zobacz więcej",
    label: "Polish",
  },
  {
    mark: "BR",
    Locale: "pt-BR",
    "Apply Now": "Registrar-se",
    "Book Now": "Reservar agora",
    "Contact Us": "Fale conosco",
    Download: "Fazer download",
    "Learn More": "Saber mais",
    Install: "Instalar",
    "Visit Site": "Visitar site",
    "Shop Now": "Comprar agora",
    "Sign Up": "Inscrever-se",
    "Get Quote": "Obter cotação",
    Subscribe: "",
    "See More": "Ver mais",
    label: "Portuguese (Brazil)",
  },
  {
    mark: "PT",
    Locale: "pt-PT",
    "Apply Now": "Candidatar-se",
    "Book Now": "Reservar já",
    "Contact Us": "Contactar-nos",
    Download: "Transferir",
    "Learn More": "Saber mais",
    Install: "Instalar",
    "Visit Site": "Visitar site",
    "Shop Now": "Comprar já",
    "Sign Up": "Inscrever-se",
    "Get Quote": "Obter orçamento",
    Subscribe: "Subscrever",
    "See More": "Ver mais",
    label: "Portuguese (Portugal)",
  },
  {
    Locale: "ro",
    "Apply Now": "Înregistrați-vă",
    "Book Now": "Rezervați acum",
    "Contact Us": "Contactați-ne",
    Download: "Descărcați",
    "Learn More": "Mai multe",
    Install: "Instalați",
    "Visit Site": "Spre site",
    "Shop Now": "Cumpărați acum",
    "Sign Up": "Înscrieți-vă",
    "Get Quote": "Ofertă de preț",
    Subscribe: "Abonați-vă",
    "See More": "",
    label: "Romanian",
  },
  {
    mark: "RU",
    Locale: "ru",
    "Apply Now": "Подать заявку",
    "Book Now": "Забронировать",
    "Contact Us": "Связаться",
    Download: "Скачать",
    "Learn More": "Подробнее",
    Install: "Установить",
    "Visit Site": "Перейти на сайт",
    "Shop Now": "Купить",
    "Sign Up": "Регистрация",
    "Get Quote": "Узнать цену",
    Subscribe: "Подписаться",
    "See More": "Ещё",
    label: "Russian",
  },
  {
    Locale: "sk",
    "Apply Now": "Odoslať žiadosť",
    "Book Now": "Rezervovať",
    "Contact Us": "Kontaktovať",
    Download: "Stiahnuť",
    "Learn More": "Ďalšie info",
    Install: "Inštalovať",
    "Visit Site": "Navštíviť web",
    "Shop Now": "Nakupovať",
    "Sign Up": "Registrovať sa",
    "Get Quote": "Cenová ponuka",
    Subscribe: "Odoberať",
    "See More": "Zobraziť viac",
    label: "Slovak",
  },
  {
    Locale: "sl",
    "Apply Now": "Zaprosite zdaj",
    "Book Now": "Rezervirajte",
    "Contact Us": "Pišite nam",
    Download: "Prenesi",
    "Learn More": "Več o tem",
    Install: "Namesti",
    "Visit Site": "Na splet. mesto",
    "Shop Now": "Začni nakup",
    "Sign Up": "Prijava",
    "Get Quote": "Dobite ponudbo",
    Subscribe: "Naročite se",
    "See More": "Več informacij",
    label: "Slovenian",
  },
  {
    Locale: "sr",
    "Apply Now": "Пријавите се",
    "Book Now": "Резервишите",
    "Contact Us": "Обратите нам се",
    Download: "Преузмите",
    "Learn More": "Сазнајте више",
    Install: "Инсталирајте",
    "Visit Site": "Посетите сајт",
    "Shop Now": "Купујте одмах",
    "Sign Up": "Региструјте се",
    "Get Quote": "Добијте понуду",
    Subscribe: "Претплатите се",
    "See More": "Погледајте још",
    label: "Serbian",
  },
  {
    mark: "SV",
    Locale: "sv",
    "Apply Now": "Ansök nu",
    "Book Now": "Boka nu",
    "Contact Us": "Kontakta oss",
    Download: "Hämta",
    "Learn More": "Läs mer",
    Install: "Installera",
    "Visit Site": "Besök webbplats",
    "Shop Now": "Handla nu",
    "Sign Up": "Registrera dig",
    "Get Quote": "Få prisförslag",
    Subscribe: "Prenumerera",
    "See More": "Visa mer",
    label: "Swedish",
  },
  {
    mark: "TH",
    Locale: "th",
    "Apply Now": "สมัครเลย",
    "Book Now": "จองเลย",
    "Contact Us": "ติดต่อเรา",
    Download: "ดาวน์โหลด",
    "Learn More": "ดูเพิ่มเติม",
    Install: "ติดตั้ง",
    "Visit Site": "เข้าชมไซต์",
    "Shop Now": "ซื้อเลย",
    "Sign Up": "สมัครใช้งาน",
    "Get Quote": "รับใบเสนอราคา",
    Subscribe: "ติดตาม",
    "See More": "",
    label: "Thai",
  },
  {
    mark: "TR",
    Locale: "tr",
    "Apply Now": "Hemen Başvurun",
    "Book Now": "Yer Ayırtın",
    "Contact Us": "Bize Ulaşın",
    Download: "İndirin",
    "Learn More": "Bilgi Edinin",
    Install: "Yükleyin",
    "Visit Site": "Siteye Gidin",
    "Shop Now": "Satın Alın",
    "Sign Up": "Kaydolun",
    "Get Quote": "Fiyat Alın",
    Subscribe: "Abone Olun",
    "See More": "Daha Fazlası",
    label: "Turkish",
  },
  {
    Locale: "uk",
    "Apply Now": "Подайте заявку",
    "Book Now": "Забронюйте",
    "Contact Us": "Наші контакти",
    Download: "Завантажте",
    "Learn More": "Докладніше",
    Install: "Установіть",
    "Visit Site": "Відвідайте сайт",
    "Shop Now": "Купуйте зараз",
    "Sign Up": "Зареєструйтеся",
    "Get Quote": "Дізнайтеся ціни",
    Subscribe: "Підпишіться",
    "See More": "Перегляньте ще",
    label: "Ukrainian",
  },
  {
    mark: "VN",
    Locale: "vi",
    "Apply Now": "Áp dụng ngay",
    "Book Now": "Đặt ngay",
    "Contact Us": "L.hệ chúng tôi",
    Download: "Tải xuống",
    "Learn More": "Tìm hiểu thêm",
    Install: "Cài đặt",
    "Visit Site": "Vào trang web",
    "Shop Now": "Mua ngay",
    "Sign Up": "Đăng ký",
    "Get Quote": "Nhận báo giá",
    Subscribe: "Theo dõi",
    "See More": "Xem thêm",
    label: "Vietnamese",
  },
  {
    Locale: "zh-CN",
    "Apply Now": "立即申请",
    "Book Now": "立即预订",
    "Contact Us": "联系我们",
    Download: "下载",
    "Learn More": "了解详情",
    Install: "安装",
    "Visit Site": "访问网站",
    "Shop Now": "立即选购",
    "Sign Up": "注册",
    "Get Quote": "获取报价",
    Subscribe: "订阅",
    "See More": "查看详情",
    label: "Chinese (PRC)",
  },
  {
    Locale: "zh-HK",
    "Apply Now": "立即申請",
    "Book Now": "立即預約",
    "Contact Us": "聯絡我們",
    Download: "下載",
    "Learn More": "瞭解詳情",
    Install: "安裝",
    "Visit Site": "瀏覽網站",
    "Shop Now": "立即選購",
    "Sign Up": "申請",
    "Get Quote": "索取報價",
    Subscribe: "訂閱",
    "See More": "查看更多",
    label: "Chinese (Hong Kong)",
  },
  {
    mark: "TW",
    Locale: "zh-TW",
    "Apply Now": "立即申請",
    "Book Now": "立即預訂",
    "Contact Us": "與我們聯絡",
    Download: "下載",
    "Learn More": "瞭解詳情",
    Install: "安裝",
    "Visit Site": "造訪網站",
    "Shop Now": "立即購買",
    "Sign Up": "註冊",
    "Get Quote": "取得報價",
    Subscribe: "訂閱",
    "See More": "查看更多",
    label: "Chinese (Taiwan)",
  },
];
export const ActionKeys = Object.keys(baseData[0]);
export const ActionMap = baseData.reduce((obj, item) => {
  if (item.mark) {
    obj[item.mark] = item;
  }
  return obj;
}, {} as Record<string, (typeof baseData)[0]>);

export const pmCallToActionOptions = [
  "LEARN_MORE",
  "GET_QUOTE",
  "APPLY_NOW",
  "SIGN_UP",
  "CONTACT_US",
  "SUBSCRIBE",
  "DOWNLOAD",
  "BOOK_NOW",
  "SHOP_NOW",
];
export const videoCallToActionOptions = [
  "LEARN_MORE",
  "GET_QUOTE",
  "APPLY_NOW",
  "SIGN_UP",
  "CONTACT_US",
  "SUBSCRIBE",
  "DOWNLOAD",
  "BOOK_NOW",
  "SHOP_NOW",
  "BUY_NOW",
  "DONATE_NOW",
  "ORDER_NOW",
  "PLAY_NOW",
  "SEE_MORE",
  "START_NOW",
  "VISIT_SITE",
  "WATCH_NOW",
];
